### PR TITLE
add ingressClassName into chart

### PR DESCRIPTION
**Pull request by wirwolf**

### CODE REVIEW

**Comment by ploxiln** [comment]
Can you squash down to a single commit, and also bump chart patch version?

**Comment by wirwolf** [comment]
You can use squashing when merging 
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests

**Comment by ploxiln** [comment]
Yeah, we know about that, but intentionally disable that option in this repository, as we'd like to see your commit separate from my merge commit.

**Comment by wirwolf** [comment]
@ploxiln done

**Comment by ploxiln** [comment]
thanks!

**Pull request merged**
